FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

WORKDIR /coco
COPY reference ./reference
COPY desc ./desc
COPY wpc_bundle.pt ./wpc_bundle.pt
COPY task_detail.json ./task_detail.json
RUN python -m zipfile -e desc/desc.zip desc

COPY requirements.txt /coco/requirements.txt
RUN pip install -r /coco/requirements.txt